### ISSUE TITLE
Legogroth16 compatibility with Rust 1.78 and above

### ISSUE THREAD

**Issue by yamdan** [docknetwork/crypto#25]
Hi @lovesh, thank you for your great work and continuous development! I found that legogroth16 does not work with Rust 1.78 and above. Running `cargo test` for legogroth16 with Rust 1.78 unexpectedly halts with the following error:

```
unsafe precondition(s) violated: ptr::copy_nonoverlapping requires that both pointer arguments are aligned and non-null and the specified memory ranges do not overlap
```

It seems to me that updating wasmer from 3.3.0 to the latest resolves this issue. However, I noticed that you already upgraded (e77a7b8) and then immediately downgraded it (fe99471). Is there any issue with the latest wasmer?

**Comment by lovesh** [comment]
Hi @yamdan . I don't remember if i ever tried with Rust 1.78 but I see from past CI logs that tests passed with Rust 1.79.

Regarding that reverted commit for upgrading wasmer, the upgrade caused some tests to fail but I don't remember what the exact error was as I didn't have time back then to investigate. So i downgraded it back.

I just upgraded to wasmer 4.3.6 and it works with Rust 1.80.1 on my local MacOS. CI is currently running with Rust 1.80.1

**Comment by yamdan** [comment]
Thank you, that’s very helpful! The issue has been resolved, so I’ll close it. By the way, in my environment, the above error occurred with Rust versions 1.78.0, 1.79.0, and 1.80.1 whenever the version of wasmer was below 4.2.0 (during tests that load wasm files like `legogroth16::circom::circuit::tests::divide_by_24`).

**Comment by yamdan** [comment]
Issue resolved, closing it.
